name: hymate_tech_task
description: "Flutter Tech Task for Hymate"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.2
  cupertino_icons: ^1.0.8
  custom_charts:
    path: packages/custom_charts
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.3
  equatable: ^2.0.7
  fl_chart: ^1.1.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_web_plugins:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.3.1
  http: ^1.5.0
  http_cache_hive_store: ^5.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  melos: ^6.3.3
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  reactive_date_time_picker: ^5.0.1
  reactive_forms: ^18.1.1
  riverpod_annotation: ^3.0.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  universal_platform: ^1.1.0

dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
